#ifndef _STRESS_H
#define _STRESS_H

#include "stress_marker.h"

#define STRESS_TEST_WORKERS 16

#define STRESS_TEST_INDIV_RATE (STRESS_TEST_RATE / STRESS_TEST_WORKERS)
#define STRESS_TEST_INDIV_GAP_NS (1000000000 / STRESS_TEST_INDIV_RATE)
#define STRESS_TEST_INDIV_GAP_CYCLES ((STRESS_TEST_INDIV_GAP_NS * 10) / 12)
#define STRESS_TEST_INDIV_GAP_RCYCLES (STRESS_TEST_INDIV_GAP_CYCLES / 16)

#endif _STRESS_H /* !_STRESS_H */