#ifndef _CONFIG_MARKER_H
#define _CONFIG_MARKER_H
#define _RL_CONFIG_SOLO_REMOTE_WORK
//#define WORK_ALLOC_RANDOMISE
#define WORK_ALLOC_STRAT ALLOC_FILL_HEAVY

#define WORKER_DO_CACHED
#define WORKER_LOCAL_CACHED_ENTRIES 5
#endif /* !_CONFIG_MARKER_H_ */