#ifndef _CONFIG_MARKER_H
#define _CONFIG_MARKER_H
// #define ENABLE_STRESS_TEST
#define _RL_CONFIG_SOLO_REMOTE_WORK
#define WORK_ALLOC_STRAT ALLOC_FILL_HEAVY
#define VERIFY_OUTPUTS
#endif /* !_CONFIG_MARKER_H_ */