#ifndef _WORK_CONFIG_MARKER_H
#define _WORK_CONFIG_MARKER_H

// #define _RL_CONFIG_SOLO_INDEP_RL_CORES

// #define _RL_CONFIG_INDEP_PIPES

// #define _RL_CONFIG_SOLO_LOCAL_WORK

#define _RL_CONFIG_SOLO_REMOTE_WORK

// #define _RL_CONFIG_INDEP_REMOTE_WORK

#endif /* !_WORK_CONFIG_MARKER_H_ */
